module.exports.messageBadReqError = 'Переданы некорректные данные';
module.exports.messageNotFoundError = 'Страница не найдена';
module.exports.messageNoAuthError = 'Недостаточно прав для выполнения операции';
module.exports.messageEmailError = 'Пользователь с таким email уже зарегистрирован';
module.exports.messageAuthError = 'Необходима авторизация';
module.exports.messageServerError = 'На сервере произошла ошибка';
module.exports.messageSignOut = 'Cookies удалены';
module.exports.messageFilmDelete = 'Фильм удален';
module.exports.messageLimiter = 'Слишком много запросов с вашего IP, попробуйте повторить попытку позже';
